"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import sys
from pathlib import Path
# Add the project root to Python path
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent  # This is /home/Alx_DjangoLearnLab/django-models
sys.path.append(str(PROJECT_ROOT))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = 'bookshelf.CustomUser'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)xi-kyxx=msxyuci)t%@z29k30)*a@(*+_q_o3bf-oyem=6&h%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []






# --- Cookie and session security ---
SESSION_COOKIE_SECURE = True                # only send session cookie over HTTPS
CSRF_COOKIE_SECURE = True                   # only send CSRF cookie over HTTPS
SESSION_COOKIE_HTTPONLY = True              # JavaScript can't read session cookie
CSRF_COOKIE_HTTPONLY = False                # usually False: templates/JS need CSRF token
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# --- SSL / HSTS / redirect ---
SECURE_SSL_REDIRECT = True                  # redirect all HTTP -> HTTPS
SECURE_HSTS_SECONDS = 31536000              # one year (adjust as needed)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
# If running behind a proxy/load-balancer that sets X-Forwarded-Proto:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# --- Browser protections ---
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
#    'books',
    'bookshelf',
    'relationship_app',
    'users',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Example CSP - tighten for your real environment, allow only the domains you use.
# Keep this minimal during development; relax only for trusted CDNs you use.
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "cdnjs.cloudflare.com")   # add CDNs you actually use
CSP_STYLE_SRC = ("'self'", "cdnjs.cloudflare.com")
CSP_IMG_SRC = ("'self'", "data:")
CSP_FONT_SRC = ("'self'",)
CSP_CONNECT_SRC = ("'self'",)
# Optionally report-only endpoint:
# CSP_REPORT_URI = '/csp-report/'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'






# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.CustomUser'


#media for profile photos
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'#we need to comment this out if the _-------_
    
DEFAULT_AUTO_FIELD = 'django.db.model.BigAutoField'



# --- Media & Image handling (profile photos) ---
# MEDIA_URL = '/media/'    
# For this recognise _-----------------------------------------------------_
BASE_DIR = globals().get('BASE_DIR', None)  # existing BASE_DIR in your settings
if BASE_DIR is not None:
    MEDIA_ROOT = BASE_DIR / 'media' if hasattr(BASE_DIR, '__truediv__') else os.path.join(BASE_DIR, 'media')

# --- Logging note (optional - useful in production) ---
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
    },
}

# Notes:
# - Use environment variables for SECRET_KEY, DB credentials, and ALLOWED_HOSTS.
# - During local development you may set DJANGO_DEBUG=1 in your environment to run with DEBUG=True.
